#!/bin/bash


if [[ $# -lt 1 ]] ; then
    echo "usage: $0 [program-name]"
    exit 1
fi

if ! [ -e /etc/qubes-release ] && ! [ -e /var/run/qubes-service/guivm ]; then
    echo "not dom0 or guivm, exiting"
    exit 0
fi

if [[ -z "${DISPLAY:+test}" ]]; then
    if [[ -n "${WAYLAND_DISPLAY:+test}" ]]; then
        echo "The widgets require Xwayland, but it is not available."
    else
        echo "DISPLAY empty or unset"
    fi >&2
    exit 1
fi

export WAYLAND_DISPLAY=

"$@"

exit_code=$?

if [[ ${exit_code} -eq 0 ]] ; then
    echo "exiting with 0"
    exit 0
else
    if xhost >/dev/null ; then
    # it was a genuine crash
        echo "exiting with 1"
        exit ${exit_code}
    else
        # XServer is down
        echo "exiting with 0"
        exit 0
    fi
fi
